platform :ios, '15.0'
use_frameworks!

target 'SwiftQueuePopUpDemo' do
    pod 'SnapKit'
end

# Older dependency podspecs may declare targets no longer supported by Xcode 27.
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            version = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
            if version.nil? || Gem::Version.new(version) < Gem::Version.new('15.0')
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
end
